pep1_official:
  image: propersoft/docker-tomcat:7.0.82-jre8
  restart: always
  volumes:
    - ./pep1/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep1/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39091:8080"
  extra_hosts:
    - "mysql:192.168.1.111"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=1024M -XX:MaxPermSize=2048m -Xms2048m -Xmx2048m
pep2_official:
  image: propersoft/docker-tomcat:7.0.82-jre8
  restart: always
  volumes:
    - ./pep2/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep2/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39092:8080"
  extra_hosts:
    - "mysql:192.168.1.111"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=1024M -XX:MaxPermSize=2048m -Xms1024m -Xmx2048m
mysql_official:
  image: mysql:5.7.14
  restart: always
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=icmp
    - MYSQL_USER=icmp
    - MYSQL_PASSWORD=U0kl0tshMi
  ports:
    - "33306:3306"
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
nginx_proxy_official:
  image: nginx:1.13.7
  restart: always
  volumes:
    - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx_proxy/log:/var/log/nginx
    - ./nginx_proxy/sites-enabled:/etc/nginx/sites-enabled
    - ./nginx_proxy/hc/hc_new:/etc/nginx/hc_new
  ports:
    - "80:80"
    - "443:443"
