pep1_official:
  image: propersoft/docker-tomcat:7.0.82-jre8
  restart: always
  volumes:
    - ./pep1/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep1/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39091:8080"
  extra_hosts:
    - "redis-pep:192.168.1.103"
    - "mysql:192.168.1.102"
    - "mongo:192.168.1.103"
    - "his-server:192.168.1.103"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=4096M -XX:MaxPermSize=8192m -Xms4096m -Xmx16384m
pep2_official:
  image: propersoft/docker-tomcat:7.0.82-jre8
  restart: always
  volumes:
    - ./pep2/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep2/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39092:8080"
  extra_hosts:
    - "redis-pep:192.168.1.103"
    - "mysql:192.168.1.102"
    - "mongo:192.168.1.103"
    - "his-server:192.168.1.103"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=4096M -XX:MaxPermSize=8192m -Xms4096m -Xmx16384m
mongo_official_cf1:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_cf1/data:/data/db
    - ./mongo_cf1/keyfile:/opt/keyfile
  ports:
    - "37101:27017"
  command: mongod --configsvr --replSet cf --port 27017
mongo_official_rs1_1:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_rs1_1/data:/data/db
    - ./mongo_rs1_1/keyfile:/opt/keyfile
  ports:
    - "37011:27017"
  command: mongod --replSet rs1
mongo_official_rs2_3:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_rs2_3/data:/data/db
    - ./mongo_rs2_3/keyfile:/opt/keyfile
  ports:
    - "37023:27017"
  command: mongod --replSet rs2
redis_official:
  image: redis:4.0.6
  restart: always
  volumes:
    - ./redis/data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  ports:
    - "36379:6379"
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
nginx_official:
  image: nginx:1.13.7
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/log:/var/log/nginx
  ports:
    - "8080:8080"
