zabbix-mysql:
  image: mysql
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=zabbix_proxy
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ports:
    - "3307:3306"
zabbix-proxy:
  image: zabbix/zabbix-proxy-mysql
  volumes:
    - ./zabbix_proxy.conf:/etc/zabbix/zabbix_proxy.conf
  environment:
    - ZBX_SERVER_HOST=59.110.158.240
    - DB_SERVER_HOST=172.28.235.114
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=zabbix_proxy
    - MYSQL_USER=zabbix
    - DB_SERVER_PORT=3307
    - MYSQL_PASSWORD=zabbix
    - ZBX_SERVER_PORT=10051
    - TZ=Asia/Shanghai
  ports:
    - 10051:10051
