pep1_official:
  image: propersoft/docker-tomcat:7.0.82-jre8
  restart: always
  volumes:
    - ./pep1/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep1/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39091:8080"
  extra_hosts:
    - "redis-pep:192.168.1.103"
    - "mysql:192.168.1.102"
    - "mongo:192.168.1.103"
    - "his-server:192.168.1.103"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=4096M -XX:MaxPermSize=8192m -Xms4096m -Xmx16384m
pep2_official:
  image: propersoft/docker-tomcat:7.0.82-jre8
  restart: always
  volumes:
    - ./pep2/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep2/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39092:8080"
  extra_hosts:
    - "redis-pep:192.168.1.103"
    - "mysql:192.168.1.102"
    - "mongo:192.168.1.103"
    - "his-server:192.168.1.103"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=4096M -XX:MaxPermSize=8192m -Xms4096m -Xmx16384m
mongo_official_cf3:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_cf3/data:/data/db
    - ./mongo_cf3/keyfile:/opt/keyfile
  ports:
    - "37103:27017"
  command: mongod --configsvr --replSet cf --port 27017
mongo_official_rs1_3:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_rs1_3/data:/data/db
    - ./mongo_rs1_3/keyfile:/opt/keyfile
  ports:
    - "37013:27017"
  command: mongod --replSet rs1
mongo_official_rs2_1:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_rs2_1/data:/data/db
    - ./mongo_rs2_1/keyfile:/opt/keyfile
  ports:
    - "37021:27017"
  command: mongod --replSet rs2
mysql_slave_official:
  image: mysql:5.7.14
  restart: always
  volumes:
    - ./mysql_slave/data:/var/lib/mysql
    - ./mysql_slave/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=ihos
    - MYSQL_USER=ihos
    - MYSQL_PASSWORD=U0kl0tshMi
  ports:
    - "33306:3306"
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
redis_slave_official:
  image: redis:4.0.6
  restart: always
  volumes:
    - ./redis_slave/data:/data
    - ./redis_slave/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - "36379:6379"
nginx_proxy_official:
  image: nginx:1.13.7
  restart: always
  volumes:
    - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx_proxy/sslconfig.conf:/etc/nginx/sslconfig.conf
    - ./nginx_proxy/log:/var/log/nginx
    - ./nginx_proxy/hc/hc_new:/etc/nginx/hc_new
    - ./nginx_proxy/sites-enabled:/etc/nginx/sites-enabled
  ports:
    - "80:80"
    - "443:443"
nginx_admin_official:
  image: nginx:1.13.7
  restart: always
  volumes:
    - ./nginx_admin/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx_admin/log:/var/log/nginx
    - ./nginx_admin/admin/www:/etc/nginx/admin
  ports:
    - "8088:80"
