mongo_official_cf2:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_cf2/data:/data/db
    - ./mongo_cf2/keyfile:/opt/keyfile
  ports:
    - "37102:27017"
  command: mongod --configsvr --replSet cf --port 27017
mongo_official_rs1_2:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_rs1_2/data:/data/db
    - ./mongo_rs1_2/keyfile:/opt/keyfile
  ports:
    - "37012:27017"
  command: mongod --replSet rs1
mongo_official_rs2_2:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_rs2_2/data:/data/db
    - ./mongo_rs2_2/keyfile:/opt/keyfile
  ports:
    - "37022:27017"
  command: mongod --replSet rs2
mysql_official:
  image: mysql:5.7.14
  restart: always
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=ihos
    - MYSQL_USER=ihos
    - MYSQL_PASSWORD=U0kl0tshMi
  ports:
    - "33306:3306"
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
redis_slave_official:
  image: redis:4.0.6
  restart: always
  volumes:
    - ./redis_slave/data:/data
    - ./redis_slave/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - "36379:6379"
mongo_log:
  image: mongo:3.2.9
  restart: always
  volumes:
    - ./mongo_log/data:/data/db
  ports:
    - "27018:27017"
  command: --auth
